### ISSUE TITLE
Errors for directories in solution without representation onn disk

### ISSUE THREAD

**Issue by McMlok** [TrimbleSolutionsCorporation/VSSonarQubeExtension#212]
Hello,

I have in my solution some "directories" like services, webs etc.. but these "directories" haven't representation od disk. On disk all projects folders are in same path level. But when I ran analysis I see many errors like this one below.

10.2.2016 7:45:18:RoslynRunner : Failed to process solution project : C:\TFS\eTrading\Main\Source\WebsInternal
10.2.2016 7:45:18:mscorlib:Could not find file 'C:\TFS\Project\Main\Source\WebsInternal'. :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at LocalHelpers.UpdateSolutionDiagnosticList(String solutionPath, INotificationManager notificationManager, Dictionary`2 externlProfileIn)

Thanks
Regards

Marti

**Comment by jmecosta** [comment]
hi, would it be ok if you could provide a small sample project. so i can support this case. thanks

**Comment by McMlok** [comment]
Yes I did some in [repository](https://github.com/McMlok/VSSonarExtensionTest)

**Comment by jmecosta** [comment]
Thanks I will try to check this soon.

**Comment by jmecosta** [comment]
@McMlok do you mind trying the last pre-release

https://github.com/TrimbleSolutionsCorporation/VSSonarQubeExtension/releases/tag/5.2.0

**Comment by jmecosta** [comment]
@McMlok ping back if issue still remains

**Comment by McMlok** [comment]
@jmecosta I try it now and no errors occurred. Sorry for late reply.

**Comment by jmecosta** [comment]
Ok great, I will put into in gallery. Thanks
