### ISSUE TITLE
Gate Check fails with  Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by StefH** [TrimbleSolutionsCorporation/VSSonarQubeExtension#272]
```
###################################
########### Gate Check  ###########
###################################

STATUS: OK 


blocker_violations GT Some(0)    
    Status : OK
    Actual Value : 0

critical_violations GT Some(0)    
    Status : OK
    Actual Value : 0

Exception During Run: Object reference not set to an instance of an object. 
    at SonarRunnerPhases.loopTimerCheck$cont@430-2(IJsonDocument response, Unit unitVar) in E:\Development\SonarQube\jmecsoftware\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\SonarRunnerPhases.fs:line 438
   at SonarRunnerPhases.loopTimerCheck$cont@406-1(OptionsData options, String content, Unit unitVar) in E:\Development\SonarQube\jmecsoftware\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\SonarRunnerPhases.fs:line 430
   at SonarRunnerPhases.EndPhase(OptionsData options) in E:\Development\SonarQube\jmecsoftware\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\SonarRunnerPhases.fs:line 465
   at Program.main(String[] argv) in E:\Development\SonarQube\jmecsoftware\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\Program.fs:line 52
```

**Comment by jmecosta** [comment]
what versions are you using of the wrapper and sonar analyser.

**Comment by jmecosta** [comment]
![image](https://user-images.githubusercontent.com/1041352/31315077-c5808702-ac18-11e7-9ca4-6a1d1d744adc.png)

**Comment by jmecosta** [comment]
@StefH please use the latest https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/tag/1.9.17 and  also the latest msbuild sonarqube runner > 4.x it should work
